name: Update Raindrop Bookmarks

on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours
  workflow_dispatch:

jobs:
  update-bookmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run bookmarks.py
        env:
          LINKDING_API_KEY: ${{ secrets.LINKDING_API_KEY }}
          LINKDING_API_ENDPOINT: ${{ secrets.LINKDING_API_ENDPOINT }}
        run: |
          python bookmarks.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./content/bookmarks
          git commit -m "updated bookmarks" || echo "No changes to commit"
          git push
